[project]
name = "fastapi-exercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.139.0",
    "pydantic[email]>=2.13.4",
    "sqlalchemy>=2.0.31",
    "psycopg2-binary>=2.9.9",
    "ruff>=0.15.20",
    "taskipy>=1.14.1",
    "uvicorn[standard]>=0.30.0",
    "pydantic-settings>=2.14.2",
    "sqlmodel>=0.0.39",
    "pyjwt>=2.13.0",
    "pwdlib[argon2]>=0.3.0",
    "tenacity>=9.1.4",
    "httpx>=0.28.1",
]
[tool.pyright]
extraPaths = ["."]

[tool.taskipy.tasks]
lint = "ruff check src/"
